CREATE TABLE users (
    UserID SERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(30) NOT NULL,
    DoctorID INTEGER,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE patientDoctor (
    UserID INTEGER NOT NULL,
    DoctorID INTEGER NOT NULL,
    PRIMARY KEY (UserID, DoctorID),
    FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (DoctorID) REFERENCES users(UserID) ON DELETE CASCADE
);
